### PR TITLE
Forward the parsing error while parsing a module to the parent module

### PR DESCRIPTION
**Pull request by ogoffart**
Otherwise we just unwrap it and the error message is not good enough

### CODE REVIEW

**Comment by ogoffart** [comment]
I did not test enough what happens when there is an error in another module than the root module.
I quickly noticed while developing on another crate that the error is not good enough.

(Would be great to have compilation error tests)

@mystor   I guess this would qualify for a 0.15.1

**Comment by ogoffart** [comment]
I took the freedom to merge the pull request as it is quite simple.

I also made another small change.

I think this qualify for 0.15.1 as it improve error reporting.

**Comment by mystor** [comment]
published as 0.15.1

**Comment by ogoffart** [comment]
Thank you!

**Pull request merged**
