### PR TITLE
Bump version

### PR DESCRIPTION
**Pull request by ogoffart**
Since there is a few new features i thought it is the time to increase the version.

### CODE REVIEW

**Comment by ogoffart** [comment]
Actually, i'm a bit unsure if it should be 0.3.3 or 0.4.
There is a potential breaking change that the cpp! macro has become more complex and may need to change the recursion_limit.
There are also quite some features.

**Comment by mystor** [comment]
Let's bump to 0.4 :-)

**Comment by ogoffart** [comment]
@mystor  If you do not object, I'll merge all the pending pull request including this version.
Then how does it work to push the next version to crates.io?

**Comment by mystor** [comment]
I can push the new version up. Throw me an email some time this week when you think the tree's ready & I'll give it a once over and publish :-)

**Pull request merged**
